# Generated by Django 3.0.5 on 2020-04-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=60)),
                ('animal', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=7)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=60, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('lost', models.DateField()),
                ('last_seen', models.CharField(blank=True, max_length=75, null=True)),
                ('address', models.CharField(blank=True, max_length=75, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('reward', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
