# Generated by Django 3.0.6 on 2020-05-19 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet_finder', '0004_auto_20200430_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.CreateModel(
            name='FoundPet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('animal', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=7)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=60, null=True)),
                ('found', models.TextField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
