# Generated by Django 3.0.7 on 2020-06-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_finder', '0006_auto_20200520_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='found/'),
        ),
    ]
